name: Backend Continuous Integration

on:
  pull_request:
    branches:
      - main
    paths:
      - "starter/backend/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --skip-lock

      - name: Run lint
        working-directory: starter/backend
        run: pipenv run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: starter/backend/Pipfile.lock

      - name: Install dependencies
        working-directory: starter/backend
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --skip-lock

      - name: Run tests
        working-directory: starter/backend
        run: pipenv run test

  build:
    needs:
      - lint
      - test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t backend:latest starter/backend